name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip extension
        run: |
          zip -r extension-${GITHUB_REF##*/}.zip . -x node_modules/** .github/** *.log
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip
          path: extension-${GITHUB_REF##*/}.zip
